version: '3'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./ui:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  api:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    ports:
      - 81:81
    volumes:
      - ./api:/go/src/api
      # wsl2の環境によって最後の/がいらない
      # - ./api:/go/src/api
    command: >
      sh -c "reflex -s -r '\.go$$' go run main.go"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: go_auth
    links:
      - 'smtp'
  ui:
    build: ./docker/vue3
    volumes:
      - ./ui:/app
    tty: true
    # build:
    #   context: .
    #   dockerfile: ./docker/vue3/Dockerfile
    # ports:
    #   - 8080:8080
    # volumes:
    #   - ./ui:/app
    # command: npm run serve

  mysql:
    image: mysql/mysql-server:5.7.28
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: go_auth
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    links:
      - mysql
    ports:
      - 8888:81

  smtp:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
